---
title: "Insect survey 2020, basic analysis"
author: "Jens Å"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  NinaR::jensAnalysis:
    highlight: tango
    fig_caption: yes
    toc: yes
---


```{r, include = F}
#Some common packages, loading rmarkdown doesn't like the messages from tidyverse, so we don't include this in the document'
require(tidyverse)
require(DBI)
require(RPostgres)
require(ggplot2)
require(xtable)
require(NinaR)
```


```{r setup, include=FALSE}
#This is optional
#I choose the 'styler' package for tidying the code to preserve indentations
#I set the cutoff for code tidying to 60, but this doesn't currently work with styler.
#Set tidy = True to get the knitr default
#I want all figures as png and pdf in high quality in a subfolder called figure 

knitr::opts_chunk$set(echo = TRUE, 
                      tidy = "styler",
                      dev = c("png", "pdf"),
                      dpi = 600,
                      fig.path = "figure/",
                      tidy.opts = list(width.cutoff = 60)
                      )

options(xtable.comment = F, 
        xtable.include.rownames = F, 
        nina.logo.y.pos = 0.15)
palette(ninaPalette())
```



```{r, include = F, eval = F}
#This connects to the gisdatabase with a DBI connection named `con`.
#Use for example dbGetQuery(con, "SELECT * FROM ....") to query the database
postgreSQLConnect(host = "gisdata-db.nina.no", 
                 dbname = "gisdata", 
                 username = "postgjest", 
                 password = "gjestpost")
```


```{r}

dat <- read.delim("long_format_data_GCF-2020-735_736_19102020.txt", sep= " ") %>% 
  as.tibble()

dat

```

